name: neural-explain
channels:
  - conda-forge
  - pytorch
  - gurobi # only if you have a license
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.8
  - onnx>=1.14
  - onnxruntime>=1.16
  - pytorch>=2.2
  - torchvision>=0.17
  - pulp>=2.7 # open-source MILP (CBC backend)
  - tqdm
  - gurobi # requires license
  - pip:
      # your in-house package (if needed)
      - oval-bab==0.0.1
